'use strict';

// Los alias castellanos aparecen en los menús; los nombres antiguos siguen activos
// para no romper automatizaciones, accesos directos ni documentación existente.
const SPANISH_COMMANDS = {
  start: 'inicio', menu: 'menu', allmenu: 'todos', help: 'ayuda',
  autostatus: 'autoestado', bcall: 'difusion', bcgc: 'difusiongrupos', block: 'bloquear', unblock: 'desbloquear', mode: 'modo', owner: 'creador', private: 'privado', public: 'publico', restart: 'reiniciar', shutdown: 'apagarbot', setname: 'cambiarnombre', timer: 'temporizador', utils: 'utilidades', mutelist: 'silenciados', chatbot: 'chatbot', gali: 'gali', seguridad: 'seguridad', 'promo-jk-bot': 'promojkbot',
  balance: 'saldo', bal: 'saldo', baltop: 'clasificacionmonedas', eboard: 'clasificacionmonedas', daily: 'diaria', work: 'trabajar', deposit: 'depositar', dep: 'depositar', withdraw: 'retirar', with: 'retirar', pay: 'pagar', transfer: 'transferir', give: 'dar', crime: 'delinquir', rob: 'robar', steal: 'robar', roulette: 'ruleta', rtl: 'ruleta', einfo: 'infoeconomia', cooldowns: 'esperas',
  note: 'nota', remind: 'recordar', time: 'hora', id: 'identificacion', uuid: 'idaleatorio', hash: 'resumen', timestamp: 'fechaunix', age: 'edad', convert: 'convertir', json: 'formatojson',
  translate: 'traducir', qr: 'codigoqr', sticker: 'sticker', toimg: 'imagen', tomp3: 'audio', tts: 'voz', blur: 'desenfocar', invert: 'invertir', crop: 'recortar', flip: 'voltear', grayscale: 'grises', removebg: 'quitafondo', enlarge: 'ampliar', logo: 'logotipo',
  song: 'cancion', video: 'video', youtube: 'youtube', insta: 'instagram', tiktok: 'tiktok', facebook: 'facebook', pinterest: 'pinterest', twitter: 'twitter', reddit: 'reddit', spotify: 'spotify', mf: 'mediafire', gdrive: 'drive', apk: 'aplicacion', playstore: 'tiendaapps', yts: 'buscarvideo', lyrics: 'letra',
  kick: 'expulsar', add: 'agregar', promote: 'ascender', demote: 'degradar', revoke: 'revocar', invite: 'invitar', mute: 'silenciar', unmute: 'reactivarusuario', kickoffline: 'expulsarinactivos', hidetag: 'avisooculto', tagall: 'mencionartodos', tagadmin: 'mencionaradmins', groupinfo: 'infogrupo', grouplink: 'enlacegrupo', join: 'unirse', leave: 'salirgrupo', open: 'abrirgrupo', close: 'cerrargrupo', onlyadmin: 'soloadmins', alertas: 'avisosgrupo', welcome: 'bienvenida', bye: 'despedida', setwelcome: 'setbienvenida', setbye: 'setdespedida', testwelcome: 'probarbienvenida', testbye: 'probar despedida', setdesc: 'cambiardescripcion', setppgc: 'cambiarfotogrupo', getbio: 'biografia', getdp: 'fotoperfil', accept: 'aceptar', poll: 'encuesta', everyonemsg: 'mensajeatodos', listonline: 'enlinea',
  antilink: 'antienlaces', anticall: 'antillamadas', antidelete: 'antiborrado', antistatus: 'antiestados', antiporno: 'antiporno', antifoto: 'antifoto', antivideo: 'antivideo', antiaudio: 'antiaudio', antisticker: 'antisticker', antidocumento: 'antidocumentos', antimedia: 'antimedia', antispam: 'antispam',
  status: 'estado', autoreacts: 'autoreacciones', autoread: 'autoleer', ai: 'ia', imagine: 'crearimagen', aivideo: 'crearvideo', aiclear: 'limpiarchatia',
  anime: 'anime', angry: 'enojar', bath: 'banar', bite: 'morder', bleh: 'mueca', blush: 'sonrojar', bored: 'aburrido', coffee: 'cafe', cry: 'llorar', cuddle: 'acurrucar', dance: 'bailar', drunk: 'borracho', eat: 'comer', handhold: 'tomar', happy: 'feliz', highfive: 'chocar', hug: 'abrazar', jump: 'saltar', kill: 'matar', kiss: 'besar', kisscheek: 'beso', laugh: 'reir', lick: 'lamer', love: 'amor', nope: 'negar', pat: 'acariciar', pout: 'puchero', punch: 'golpear', push: 'empujar', run: 'correr', sad: 'triste', scared: 'asustado', seduce: 'seducir', shy: 'timido', slap: 'bofetada', sleep: 'dormir', smile: 'sonreir', smoke: 'fumar', spit: 'escupir', step: 'pisar', think: 'pensar', walk: 'caminar', wave: 'saludar', wink: 'guinar',
  joke: 'chiste', meme: 'meme', dare: 'reto', truth: 'verdad', ascii: 'textoascii', roast: 'broma', compliment: 'piropo', ship: 'compatibilidad', emojimix: 'mezclaemoji', character: 'personajeanime', quote: 'frase', fact: 'dato', trivia: 'trivia', coinflip: 'moneda', economy: 'economia', profile: 'perfil', roll: 'dado', riddle: 'adivinanza', wouldyourather: 'queprefieres',
  ping: 'latencia', dp: 'foto', vv: 'veruna', base64: 'codificar', shorturl: 'enlacecorto', calc: 'calcular', weather: 'clima', github: 'github', ipinfo: 'infoip', tempmail: 'correotemporal', fakeinfo: 'datosejemplo', binlookup: 'consultabin', whois: 'dominio', dnslookup: 'consultadns', portscan: 'revisarpuerto', screenshot: 'capturaweb', define: 'definir', google: 'buscarenweb', wiki: 'wikipedia', npm: 'paquete',
  hack: 'bromahack', repo: 'repositorio', spam: 'spam', smsbomb: 'bombasms', callbomb: 'bomballamada', crash: 'bloqueo', freeze: 'congelar', lag: 'retraso', bug: 'error', locspam: 'ubicacionrepetida', vcardspam: 'contactosrepetidos', buttonspam: 'botonesrepetidos', pollspam: 'encuestarepetida', contactspam: 'contactosrepetidos', xrestart: 'reinicioforzado', xshutdown: 'apagadoforzado', ghostmode: 'modofantasma', nuke: 'limpiargrupo', deleteall: 'borrartodo', antibug: 'antierrores',
  quran: 'coran', hadith: 'hadiz', prayer: 'oracion', qibla: 'qibla', asmaulhusna: 'nombresdivinos', uptime: 'tiempoactivo', serverinfo: 'infoservidor', speedtest: 'pruebavelocidad', report: 'reportar', device: 'dispositivo', runtime: 'ejecucion',
  password: 'contrasena', morse: 'morse', binary: 'binario', hex: 'hexadecimal', pastebin: 'pegado', news: 'noticias', crypto: 'criptomonedas', movie: 'pelicula', manga: 'manga', snipe: 'recuperar', editmsg: 'editarmensaje', react: 'reaccionar', send: 'enviar', forward: 'reenviar', clear: 'limpiar', save: 'guardar', get: 'obtener', backup: 'respaldo', restore: 'restaurar', clone: 'clonar', mention: 'mencionar', tagme: 'mencioname', mycmd: 'micomando',
  // Alias del RPG: accesibles sin la W final; también se mantienen las formas anteriores.
  warcraft: 'warcraft', warcraftmenu: 'warcraft', ayudaw: 'warcraft', comandosw: 'warcraft', tutorialw: 'tutorial', tutorialwarcraft: 'tutorial', loginw: 'login', pjnombre: 'nombredelpersonaje', clase: 'clase', statusw: 'estadopersonaje', estadow: 'estadopersonaje', personajew: 'fichapersonaje', inventariow: 'inventario', equiparw: 'equipar', usarw: 'usar', pocionw: 'usar', enemigosw: 'enemigos', buscarw: 'buscar', cazarw: 'buscar', atacarw: 'atacar', attackw: 'atacar', habilidadw: 'habilidad', skillw: 'habilidad', hechizow: 'habilidad', huirw: 'huir', misionesw: 'misiones', aceptarmisionw: 'aceptarmision', aceptarmision: 'aceptarmision', cancelarmisionw: 'cancelarmision', cancelarmision: 'cancelarmision', mazmorrasw: 'mazmorras', mazmorraw: 'mazmorra', tiendaw: 'tienda', comprarw: 'comprar', confirmarcompra: 'confirmarcompra', cancelarcompra: 'cancelarcompra', talentosw: 'talentos', mapaw: 'mapa', zonasw: 'mapa', viajarw: 'viajar', profesionesw: 'profesiones', aprenderw: 'aprender', recolectarw: 'recolectar', recetasw: 'recetas', fabricarw: 'fabricar', diariaw: 'recompensadiaria', logrosw: 'logros', monturasw: 'monturas', comprarmonturaw: 'comprarmontura', grupow: 'gruporpg', subastaw: 'subasta', venderw: 'vender', comprarsubastaw: 'comprarsubasta', correow: 'correo', reclamarmailw: 'reclamarmail', enviarmailw: 'enviarmail', encantamientosw: 'encantamientos', encantarw: 'encantar', guildw: 'hermandad', duelo: 'duelo', desafiar: 'desafiar', aceptarduel: 'aceptarduelo', aceptarduelo: 'aceptarduelo', atacarduel: 'atacarduelo', dueloatacar: 'atacarduelo', habilidadduel: 'habilidadduelo', rendirse: 'rendirse', comerciar: 'comerciar', trade: 'comerciar', dar: 'ofrecer', aceptc: 'aceptarcomercio', cancelc: 'cancelarcomercio', darporreembolso: 'darporreembolso', reembolso: 'reembolso', aceptarreembolso: 'aceptarreembolso', cancelarreembolso: 'cancelarreembolso', '-reembolso': '-reembolso', agrow: 'agro', curarw: 'curar', especializacionw: 'especializacion'
};

for (const [command, alias] of Object.entries(SPANISH_COMMANDS)) {
  if (alias.includes(' ')) SPANISH_COMMANDS[command] = alias.replace(/\s+/g, '');
}
const COMMANDS_BY_SPANISH = Object.fromEntries(Object.entries(SPANISH_COMMANDS).map(([command, alias]) => [alias.toLowerCase(), command]));
function canonicalCommand(name) { const key = String(name || '').toLowerCase(); return COMMANDS_BY_SPANISH[key] || key; }
function spanishCommand(name) { const key = String(name || '').toLowerCase(); return SPANISH_COMMANDS[key] || key; }
module.exports = { SPANISH_COMMANDS, COMMANDS_BY_SPANISH, canonicalCommand, spanishCommand };
