const crypto = require('crypto');

const MAX_LEVEL = 80;
const CLASS_CONFIG = {
  warrior: { label: 'Guerrero', emoji: '⚔️', baseAttack: 8, baseDefense: 8, talent: 'Filo de batalla', skills: { golpe: { name: 'Golpe poderoso', multiplier: 1.35, cooldown: 2 }, escudo: { name: 'Bloqueo defensivo', multiplier: 0.65, cooldown: 3 } } },
  mago: { label: 'Mago', emoji: '🔮', baseAttack: 11, baseDefense: 4, talent: 'Chispa arcana', skills: { hechizo: { name: 'Descarga arcana', multiplier: 1.55, cooldown: 3 }, barrera: { name: 'Barrera arcana', multiplier: 0.5, cooldown: 3 } } },
  picaro: { label: 'Pícaro', emoji: '🗡️', baseAttack: 10, baseDefense: 5, talent: 'Golpe bajo', skills: { emboscada: { name: 'Emboscada', multiplier: 1.8, cooldown: 3 }, esquivar: { name: 'Evasión', multiplier: 0.4, cooldown: 3 } } }
};
const ITEMS = {
  rusty_sword: { name: 'Espada oxidada', slot: 'weapon', attack: 3, defense: 0, level: 1, price: 25 },
  apprentice_staff: { name: 'Bastón de aprendiz', slot: 'weapon', attack: 4, defense: 0, level: 1, price: 30 },
  shadow_dagger: { name: 'Daga de sombra', slot: 'weapon', attack: 4, defense: 0, level: 1, price: 30 },
  village_armor: { name: 'Armadura de la aldea', slot: 'armor', attack: 0, defense: 3, level: 1, price: 40 },
  iron_blade: { name: 'Hoja de hierro', slot: 'weapon', attack: 10, defense: 0, level: 10, price: 180 },
  arcane_staff: { name: 'Bastón arcano', slot: 'weapon', attack: 14, defense: 0, level: 18, price: 350 },
  nightfang: { name: 'Colmillo nocturno', slot: 'weapon', attack: 16, defense: 0, level: 22, price: 420 },
  dungeon_plate: { name: 'Placas de la cripta', slot: 'armor', attack: 0, defense: 14, level: 12, price: 450 },
  health_potion: { name: 'Poción de salud', slot: 'consumable', heal: 30, level: 1, price: 20 }
};
const ENEMIES = {
  lobo: { name: 'Lobo sombrío', level: 1, hp: 55, attack: 7, defense: 2, xp: 35, gold: [8, 18], quest: 'wolves', loot: ['health_potion'] },
  bandido: { name: 'Bandido del camino', level: 8, hp: 150, attack: 18, defense: 8, xp: 100, gold: [25, 55], quest: 'bandits', loot: ['iron_blade', 'health_potion'] },
  ogro: { name: 'Ogro de la montaña', level: 15, hp: 330, attack: 32, defense: 16, xp: 260, gold: [70, 150], loot: ['dungeon_plate', 'nightfang'] }
};
const QUESTS = [
  { id: 'wolves', name: 'Lobos de la frontera', description: 'Derrota 3 lobos sombríos.', level: 1, xp: 90, gold: 45, goal: 3 },
  { id: 'crypt', name: 'Ecos de la cripta', description: 'Completa una mazmorra.', level: 5, xp: 260, gold: 140, goal: 1 },
  { id: 'bandits', name: 'Bandidos del camino', description: 'Derrota 5 bandidos.', level: 8, xp: 420, gold: 260, goal: 5 }
];
const DUNGEONS = [
  { id: 'crypt', name: 'Cripta de los Caídos', level: 5, minGold: 100, maxGold: 240, xp: 220, item: 'dungeon_plate', boss: 'bandido' },
  { id: 'forge', name: 'Forja de Hierro', level: 12, minGold: 240, maxGold: 520, xp: 480, item: 'iron_blade', boss: 'ogro' },
  { id: 'night', name: 'Cámara de la Noche', level: 20, minGold: 500, maxGold: 900, xp: 850, item: 'nightfang', boss: 'ogro' }
];
function normalizePhone(value) { return String(value || '').replace(/\D/g, ''); }
function xpForLevel(level) { return level >= MAX_LEVEL ? 0 : Math.floor(100 * Math.pow(level, 1.35)); }
function ensureRoot(botData) { botData.warcraft ||= { players: {}, accounts: {}, trades: {}, guilds: {}, sessions: {}, combat: {}, cooldowns: {}, duels: {}, duelRequests: {}, pendingPurchases: {} }; const r = botData.warcraft; for (const key of ['players','accounts','trades','guilds','sessions','combat','cooldowns','duels','duelRequests','pendingPurchases']) r[key] ||= {}; return r; }
function playerId(jid) { return String(jid || '').split('@')[0].split(':')[0].replace(/\D/g, ''); }
function ensurePlayer(botData, jid, name = 'Aventurero') { const root = ensureRoot(botData); const id = playerId(jid); const p = root.players[id]; if (!p) return null; normalizePlayer(p, name); return p; }
function normalizePlayer(p, fallbackName = 'Aventurero') { p.inventory ||= []; p.equipment ||= {}; p.talents ||= {}; p.quests ||= {}; p.guildId ||= null; p.gold = Number(p.gold || 0); p.xp = Number(p.xp || 0); p.level = Number(p.level || 1); p.name ||= fallbackName; p.maxHp = Number(p.maxHp || 100 + p.level * 10); p.hp = Math.min(Number(p.hp ?? p.maxHp), p.maxHp); p.cooldowns ||= {}; recalc(p); return p; }
function createPlayer(botData, jid, name, classKey) { const root = ensureRoot(botData); const id = playerId(jid); if (root.players[id]) return { error: 'Ya tienes un personaje creado.' }; if (!CLASS_CONFIG[classKey]) return { error: 'Clase inválida. Usa warrior, mago o picaro.' }; const p = { id, jid, name: String(name).trim().slice(0, 20), classKey, level: 1, xp: 0, gold: 80, hp: 110, maxHp: 110, talentPoints: 0, talents: {}, inventory: ['rusty_sword', 'village_armor', 'health_potion'], equipment: { weapon: 'rusty_sword', armor: 'village_armor' }, quests: {}, cooldowns: {}, createdAt: new Date().toISOString() }; root.players[id] = p; recalc(p); return { player: p }; }
function recalc(p) { const cls = CLASS_CONFIG[p.classKey] || CLASS_CONFIG.warrior; const weapon = ITEMS[p.equipment?.weapon] || {}; const armor = ITEMS[p.equipment?.armor] || {}; p.attack = cls.baseAttack + Number(weapon.attack || 0) + Number(p.talents.attack || 0); p.defense = cls.baseDefense + Number(armor.defense || 0) + Number(p.talents.defense || 0); p.maxHp = 100 + p.level * 10 + Number(p.talents.vitality || 0) * 5; p.hp = Math.min(Number(p.hp ?? p.maxHp), p.maxHp); p.gs = Math.max(1, p.level * 10 + p.attack * 2 + p.defense * 2); return p; }
function grantXp(p, amount) { const events = []; if (p.level >= MAX_LEVEL) return events; p.xp += Number(amount || 0); while (p.level < MAX_LEVEL && p.xp >= xpForLevel(p.level)) { p.xp -= xpForLevel(p.level); p.level++; p.talentPoints = Number(p.talentPoints || 0) + 1; p.hp = p.maxHp; events.push(`🎉 Subiste al nivel ${p.level}. Ganaste 1 punto de talento.`); } recalc(p); return events; }
function progressQuest(p, id, amount = 1) { const q = QUESTS.find(x => x.id === id); if (!q || p.level < q.level) return null; p.quests[id] ||= { progress: 0, completed: false }; const s = p.quests[id]; if (!s.completed) s.progress = Math.min(q.goal, s.progress + amount); if (!s.completed && s.progress >= q.goal) { s.completed = true; p.gold += q.gold; return { q, levels: grantXp(p, q.xp) }; } return null; }
function listItems(p) { return p.inventory.map((id, index) => ({ index: index + 1, id, ...(ITEMS[id] || { name: id }) })); }
function inventoryCounts(p) { const counts = {}; for (const id of p?.inventory || []) counts[id] = (counts[id] || 0) + 1; return counts; }
function findItemId(value) { const q = String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); if (!q) return null; const direct = Object.keys(ITEMS).find(id => id.toLowerCase() === q); if (direct) return direct; return Object.entries(ITEMS).find(([, item]) => { const n = item.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); return n === q || n.includes(q) || (q === 'posion' && n.includes('pocion')); })?.[0] || null; }
function removeItems(p, items = []) { const copy = [...(p.inventory || [])]; for (const id of items) { const i = copy.indexOf(id); if (i < 0) return false; copy.splice(i, 1); } p.inventory = copy; return true; }
function equip(p, idOrName) { const id = findItemId(idOrName); const item = ITEMS[id]; if (!item) return { error: 'Objeto inexistente.' }; if (!p.inventory.includes(id)) return { error: 'No tienes ese objeto.' }; if (!['weapon','armor'].includes(item.slot)) return { error: 'Ese objeto no se puede equipar.' }; if (p.level < item.level) return { error: `Necesitas nivel ${item.level}.` }; p.equipment[item.slot] = id; recalc(p); return { item }; }
function useItem(p, idOrName) { const id = findItemId(idOrName); const item = ITEMS[id]; if (!item || item.slot !== 'consumable') return { error: 'Ese objeto no es un consumible.' }; if (!removeItems(p, [id])) return { error: 'No tienes ese objeto.' }; const before = p.hp; p.hp = Math.min(p.maxHp, p.hp + item.heal); return { item, healed: p.hp - before }; }
function buy(p, id) { const item = ITEMS[id]; if (!item) return { error: 'Objeto inexistente.' }; if (p.level < item.level) return { error: `Necesitas nivel ${item.level}.` }; if (p.gold < item.price) return { error: `Te faltan ${item.price - p.gold} de oro.` }; p.gold -= item.price; p.inventory.push(id); if (item.slot === 'weapon' && (!p.equipment.weapon || item.attack > (ITEMS[p.equipment.weapon]?.attack || 0))) p.equipment.weapon = id; if (item.slot === 'armor' && item.defense > (ITEMS[p.equipment.armor]?.defense || 0)) p.equipment.armor = id; recalc(p); return { item }; }
function startCombat(root, p, enemyId = 'lobo') { const base = ENEMIES[enemyId]; if (!base) return { error: 'Enemigo inválido. Usa /enemigosW.' }; if (p.level < base.level) return { error: `Necesitas nivel ${base.level}.` }; if (root.combat[p.id]?.status === 'active') return { error: 'Ya estás en combate. Usa /atacarW.' }; const combat = { id: crypto.randomBytes(4).toString('hex'), playerId: p.id, enemyId, enemy: { ...base, maxHp: base.hp }, status: 'active', round: 1, log: [], startedAt: new Date().toISOString() }; root.combat[p.id] = combat; return { combat }; }
function combatAttack(root, p, skillId = 'auto') { const c = root.combat[p.id]; if (!c || c.status !== 'active') return { error: 'No estás en combate. Usa /buscarW lobo.' }; const cls = CLASS_CONFIG[p.classKey] || CLASS_CONFIG.warrior; const skill = skillId !== 'auto' ? cls.skills?.[skillId] : null; const cd = Number(p.cooldowns?.[skillId] || 0); if (skill && cd > 0) return { error: `Esa habilidad estará lista en ${cd} turno(s).` }; let raw = p.attack * (skill?.multiplier || (0.85 + Math.random() * 0.35)); const critical = Math.random() < (skill ? 0.15 : 0.1); if (critical) raw *= 1.75; const damage = Math.max(1, Math.floor(raw - c.enemy.defense * 0.35)); c.enemy.hp -= damage; const log = [`Ronda ${c.round}: ${skill ? skill.name : 'Ataque básico'} inflige ${damage}${critical ? ' de daño crítico' : ' de daño'}.`]; if (skill) p.cooldowns[skillId] = skill.cooldown; for (const k of Object.keys(p.cooldowns)) if (k !== skillId && p.cooldowns[k] > 0) p.cooldowns[k]--; if (c.enemy.hp <= 0) { c.status = 'victory'; const gold = c.enemy.gold[0] + Math.floor(Math.random() * (c.enemy.gold[1] - c.enemy.gold[0] + 1)); p.gold += gold; const levels = grantXp(p, c.enemy.xp); const quest = c.enemy.quest ? progressQuest(p, c.enemy.quest) : null; const loot = c.enemy.loot?.length && Math.random() < 0.45 ? c.enemy.loot[Math.floor(Math.random() * c.enemy.loot.length)] : null; if (loot) p.inventory.push(loot); recalc(p); root.combat[p.id] = c; return { victory: true, damage, gold, loot, levels, quest, log }; } const incoming = Math.max(1, Math.floor(c.enemy.attack * (0.85 + Math.random() * 0.3) - p.defense * 0.45)); p.hp = Math.max(0, p.hp - incoming); log.push(`${c.enemy.name} te golpea por ${incoming}.`); c.round++; if (p.hp <= 0) { p.hp = Math.max(1, Math.floor(p.maxHp * 0.25)); c.status = 'defeat'; log.push('Has sido derrotado y vuelves con el 25% de vida.'); } c.log.push(...log); return { damage, incoming, critical, log, combat: c }; }
function createDuel(root, challenger, targetId) { if (!root.players[targetId]) return { error: 'El jugador objetivo no tiene personaje.' }; if (targetId === challenger.id) return { error: 'No puedes retarte a ti mismo.' }; const id = crypto.randomBytes(4).toString('hex').toUpperCase(); root.duels[id] = { id, status: 'pending', players: [challenger.id, targetId], turns: 0, hp: {}, log: [], createdAt: new Date().toISOString() }; root.duelRequests[targetId] = id; return { duel: root.duels[id] }; }
function acceptDuel(root, player) { const id = root.duelRequests[player.id]; const duel = id && root.duels[id]; if (!duel || duel.status !== 'pending') return { error: 'No tienes ningún desafío pendiente.' }; duel.status = 'active'; duel.turn = duel.players[0]; duel.hp = Object.fromEntries(duel.players.map(pid => [pid, root.players[pid].maxHp])); delete root.duelRequests[player.id]; return { duel }; }
function duelAttack(root, player, skillId = 'auto') { const duel = Object.values(root.duels).find(d => d.status === 'active' && d.players.includes(player.id)); if (!duel) return { error: 'No estás en un duelo.' }; if (duel.turn !== player.id) return { error: 'Espera el turno del otro jugador.' }; const targetId = duel.players.find(id => id !== player.id); const target = root.players[targetId]; const cls = CLASS_CONFIG[player.classKey] || CLASS_CONFIG.warrior; const skill = skillId !== 'auto' ? cls.skills?.[skillId] : null; if (skill && Number(player.cooldowns?.[skillId] || 0) > 0) return { error: `Habilidad en enfriamiento: ${player.cooldowns[skillId]} turno(s).` }; const critical = Math.random() < (skill ? 0.15 : 0.1); const raw = player.attack * (skill?.multiplier || (0.85 + Math.random() * 0.35)) * (critical ? 1.75 : 1); const damage = Math.max(1, Math.floor(raw - target.defense * 0.35)); duel.hp[targetId] -= damage; duel.turns++; duel.log.push(`${player.name} inflige ${damage}${critical ? ' crítico' : ''} a ${target.name}.`); if (skill) player.cooldowns[skillId] = skill.cooldown; if (duel.hp[targetId] <= 0) { duel.status = 'completed'; duel.winner = player.id; return { duel, victory: true, damage }; } duel.turn = targetId; return { duel, damage, critical }; }
function dungeon(p, id) { const d = DUNGEONS.find(x => x.id === id) || DUNGEONS.find(x => p.level >= x.level); if (!d) return { error: 'No hay mazmorras disponibles para tu nivel.' }; if (p.level < d.level) return { error: `Necesitas nivel ${d.level}.` }; const reward = Math.floor(d.minGold + Math.random() * (d.maxGold - d.minGold + 1)); p.gold += reward; p.inventory.push(d.item); const levels = grantXp(p, d.xp); const quest = progressQuest(p, 'crypt'); recalc(p); return { dungeon: d, reward, levels, quest }; }
function guild(botData, action, p, name) { const root = ensureRoot(botData); if (action === 'create') { if (p.guildId) return { error: 'Ya perteneces a una guild.' }; const id = crypto.randomBytes(3).toString('hex'); root.guilds[id] = { id, name: String(name || 'Hermandad').slice(0, 24), leader: p.id, members: [p.id], bank: 0 }; p.guildId = id; return { guild: root.guilds[id] }; } if (action === 'info') return { guild: p.guildId ? root.guilds[p.guildId] : null }; return { error: 'Acción de guild inválida.' }; }
function formatStatus(p) { recalc(p); const cls = CLASS_CONFIG[p.classKey] || CLASS_CONFIG.warrior; return `${cls.emoji} *WARCRAFT · ${p.name}*\n${cls.label} · Nivel ${p.level}/${MAX_LEVEL} · GS ${p.gs}\n❤️ Vida ${p.hp}/${p.maxHp} · ✨ XP ${p.xp}/${xpForLevel(p.level) || 'MAX'} · 💰 Oro ${p.gold}\n⚔️ Ataque ${p.attack} · 🛡️ Defensa ${p.defense}\n🎯 Talentos disponibles: ${p.talentPoints || 0}`; }
module.exports = { MAX_LEVEL, CLASS_CONFIG, ITEMS, ENEMIES, QUESTS, DUNGEONS, normalizePhone, xpForLevel, ensureRoot, ensurePlayer, createPlayer, recalc, grantXp, progressQuest, listItems, inventoryCounts, findItemId, removeItems, equip, useItem, buy, startCombat, combatAttack, createDuel, acceptDuel, duelAttack, dungeon, guild, formatStatus };
